// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using EmbassyAassetManagementAPI.Models;

#nullable disable

namespace EmbassyAassetManagementAPI.Migrations
{
    [DbContext(typeof(EmbassyAssetManagementContext))]
    [Migration("20260121100400_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmbassyAassetManagementAPI.Models.Loginauditlog", b =>
                {
                    b.Property<long>("Logid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("logid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Logid"));

                    b.Property<string>("Appname")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("appname");

                    b.Property<string>("Asinfo")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("asinfo");

                    b.Property<string>("Browserinfo")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("browserinfo");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<string>("Countrycode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("countrycode");

                    b.Property<string>("Ipaddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ipaddress");

                    b.Property<string>("Isp")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("isp");

                    b.Property<string>("Latitude")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("latitude");

                    b.Property<DateTime?>("Loggedinat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("loggedinat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Longitude")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("longitude");

                    b.Property<string>("Org")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("org");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("region");

                    b.Property<string>("Regionname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("regionname");

                    b.Property<string>("Timezone")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("timezone");

                    b.Property<string>("Username")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("username");

                    b.Property<string>("Zipcode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("zipcode");

                    b.HasKey("Logid")
                        .HasName("loginauditlogs_pkey");

                    b.ToTable("loginauditlogs", (string)null);
                });

            modelBuilder.Entity("EmbassyAassetManagementAPI.Models.TblMenuPerm", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("permission_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PermissionId"));

                    b.Property<bool?>("CanDelete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("can_delete")
                        .HasDefaultValueSql("false");

                    b.Property<bool?>("CanRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("can_read")
                        .HasDefaultValueSql("false");

                    b.Property<bool?>("CanWrite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("can_write")
                        .HasDefaultValueSql("false");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("character varying")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasDefaultValueSql("true");

                    b.Property<int?>("MenuId")
                        .HasColumnType("integer")
                        .HasColumnName("menu_id");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("character varying")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("PermissionId")
                        .HasName("tbl_menu_perm_pkey");

                    b.HasIndex("MenuId");

                    b.HasIndex(new[] { "RoleId", "MenuId" }, "tbl_menu_perm_role_id_menu_id_key")
                        .IsUnique();

                    b.ToTable("tbl_menu_perm", (string)null);
                });

            modelBuilder.Entity("EmbassyAassetManagementAPI.Models.TblPopupMenu", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("menu_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MenuId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("character varying")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Helperurl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("helperurl");

                    b.Property<string>("Href")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("href");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("icon");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasDefaultValueSql("true");

                    b.Property<string>("MenuName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("menu_name");

                    b.Property<int?>("Orderby")
                        .HasColumnType("integer")
                        .HasColumnName("orderby");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("character varying")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("MenuId")
                        .HasName("tbl_popup_menu_pkey");

                    b.ToTable("tbl_popup_menu", (string)null);
                });

            modelBuilder.Entity("EmbassyAassetManagementAPI.Models.TblRoleMaster", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("character varying")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasDefaultValueSql("true");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_name");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("character varying")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("RoleId")
                        .HasName("tbl_role_master_pkey");

                    b.HasIndex(new[] { "RoleName" }, "tbl_role_master_role_name_key")
                        .IsUnique();

                    b.ToTable("tbl_role_master", (string)null);
                });

            modelBuilder.Entity("EmbassyAassetManagementAPI.Models.TblUserMaster", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .HasColumnType("character varying")
                        .HasColumnName("address");

                    b.Property<int?>("Candidateid")
                        .HasColumnType("integer")
                        .HasColumnName("candidateid");

                    b.Property<string>("Companyname")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("companyname");

                    b.Property<string>("Companytype")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("companytype");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("character varying")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date");

                    b.Property<int?>("Deviceid")
                        .HasColumnType("integer")
                        .HasColumnName("deviceid");

                    b.Property<string>("EmailId")
                        .HasColumnType("character varying")
                        .HasColumnName("email_id");

                    b.Property<string>("Empid")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("empid");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Lastname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lastname");

                    b.Property<string>("MobileNo")
                        .HasColumnType("character varying")
                        .HasColumnName("mobile_no");

                    b.Property<string>("Name")
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.Property<string>("Nationalid")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nationalid");

                    b.Property<int?>("Otp")
                        .HasColumnType("integer")
                        .HasColumnName("otp");

                    b.Property<string>("Password")
                        .HasColumnType("character varying")
                        .HasColumnName("password");

                    b.Property<int?>("Salesmanid")
                        .HasColumnType("integer")
                        .HasColumnName("salesmanid");

                    b.Property<string>("Token")
                        .HasColumnType("character varying")
                        .HasColumnName("token");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("character varying")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_date");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("tbl_user_master_pkey");

                    b.ToTable("tbl_user_master", (string)null);
                });

            modelBuilder.Entity("EmbassyAassetManagementAPI.Models.TblUserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("character varying")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("is_active")
                        .HasDefaultValueSql("true");

                    b.Property<int?>("Parentid")
                        .HasColumnType("integer")
                        .HasColumnName("parentid");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("character varying")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("UserId", "RoleId")
                        .HasName("tbl_user_roles_pkey");

                    b.HasIndex("Parentid");

                    b.HasIndex("RoleId");

                    b.ToTable("tbl_user_roles", (string)null);
                });

            modelBuilder.Entity("EmbassyAassetManagementAPI.Models.TblMenuPerm", b =>
                {
                    b.HasOne("EmbassyAassetManagementAPI.Models.TblPopupMenu", "Menu")
                        .WithMany("TblMenuPerms")
                        .HasForeignKey("MenuId")
                        .HasConstraintName("tbl_menu_perm_menu_id_fkey");

                    b.HasOne("EmbassyAassetManagementAPI.Models.TblRoleMaster", "Role")
                        .WithMany("TblMenuPerms")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("tbl_menu_perm_role_id_fkey");

                    b.Navigation("Menu");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EmbassyAassetManagementAPI.Models.TblUserRole", b =>
                {
                    b.HasOne("EmbassyAassetManagementAPI.Models.TblUserMaster", "Parent")
                        .WithMany("TblUserRoleParents")
                        .HasForeignKey("Parentid")
                        .HasConstraintName("fk_parent_role");

                    b.HasOne("EmbassyAassetManagementAPI.Models.TblRoleMaster", "Role")
                        .WithMany("TblUserRoles")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("tbl_user_roles_role_id_fkey");

                    b.HasOne("EmbassyAassetManagementAPI.Models.TblUserMaster", "User")
                        .WithMany("TblUserRoleUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("tbl_user_roles_user_id_fkey");

                    b.Navigation("Parent");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EmbassyAassetManagementAPI.Models.TblPopupMenu", b =>
                {
                    b.Navigation("TblMenuPerms");
                });

            modelBuilder.Entity("EmbassyAassetManagementAPI.Models.TblRoleMaster", b =>
                {
                    b.Navigation("TblMenuPerms");

                    b.Navigation("TblUserRoles");
                });

            modelBuilder.Entity("EmbassyAassetManagementAPI.Models.TblUserMaster", b =>
                {
                    b.Navigation("TblUserRoleParents");

                    b.Navigation("TblUserRoleUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
